### ISSUE TITLE
Vague documentation regarding the pdns pipe backend

### ISSUE THREAD

**Issue by kostich** [catalyst/acmeproxy#12]
Hi,

I'm trying to configure acmeproxy with my PDNS 4 server but I do not understand the lines describing the `/etc/powerdns/pdns.d/acmeproxy.conf` file.  To be precise, the line containing the `pipe-command` setting.

If I set it to path `/opt/acmeproxy/backend`, PowerDNS doesn't restart. This file `backend` doesn't even exist.

Am I missing something? How to you properly configure acmeproxy pdns pipe backend and how then you start the acmeproxy webserver (/opt/acmeproxy/manage.py runserver)?

Thanks in advance.

**Comment by fincham** [comment]
Sorry about that, I forgot to ship the "backend" script itself.

Essentially it just runs the "pipeapi" management command. I'll fix this up so it's included in the repository.

**Comment by fincham** [comment]
Backend is now included in the repo.
